package.json
Changelog
---------
- Instructed package.json to point to org-scoped package name
Checklist
---------
=> Scope package release to Paion Data organizatin on NPM

docs/docusaurus.config.js, packages/messier-61-editor/Lexical/LexicalEditor.module.css, packages/messier-61-external-brain/ExternalBrain.module.css, packages/messier-61-external-brain/ExternalBrain.tsx, packages/messier-61-graph/D3Graph/D3Graph.module.css, packages/messier-61-graph/D3Graph/D3Graph.tsx, packages/messier-61-graph/GraphDecorator.test.ts, packages/messier-61-graph/GraphDecorator.ts
Changelog
---------
修改画布的CSS样式
Checklist
---------
=> Add graph css

packages/messier-61-graph/package.json, packages/messier-61-graph/tsconfig.json
Changelog
---------
- Create tsconfig.json and package.json file under packages/messier-61-graph
Checklist
---------
=> Mack a NPM Package

packages/messier-61-graph/graph-visualization/models/Graph.test.ts, packages/messier-61-graph/graph-visualization/models/Graph.ts, packages/messier-61-graph/graph-visualization/models/Node.test.ts, packages/messier-61-graph/graph-visualization/models/Relationship.test.ts, packages/messier-61-graph/package-lock.json, packages/messier-61-graph/package.json
Changelog
---------
- Add test for `Node.ts`, `Graph.ts`, `Relationship.ts`.
- Incorporated [Lodash](https://lodash.com/) into project
Checklist
---------
=> Test Graph Model

packages/messier-61-graph/graph-visualization/GraphVisualizer/Graph/visualization/ForceSimulation.test.ts, packages/messier-61-graph/graph-visualization/GraphVisualizer/Graph/visualization/ForceSimulation.ts
Changelog
---------
- Add `ForceSimulation.test.ts` under packages/messier-61-graph/graph-visualization/GraphVisualizer/Graph/visualization/.
- Tests to get node coordinates.
- Tests to get the radius of a ring with evenly distributed nodes.
Checklist
---------
=> Add Circular Layout Test

.github/workflows/ci-cd.yml
Changelog
---------
- Deduplicate CI/CD logics across "test" and "release" action files by consolidating them into a single action file (existing test & release actions have been disabled)
Checklist
---------
=> Consolidate CI/CD definitions

README.md, packages/messier-61-app/package.json, packages/messier-61-app/src/App.jsx, packages/messier-61-app/src/components/Team.jsx, packages/messier-61-app/src/components/about.jsx, packages/messier-61-app/src/components/footer.jsx, packages/messier-61-app/src/components/header.jsx, packages/messier-61-app/src/components/navigation.jsx, packages/messier-61-app/src/components/services.jsx, packages/messier-61-app/src/data/data.json, packages/messier-61-app/src/i18n.js, packages/messier-61-app/src/index.js, packages/messier-61-app/yarn.lock
Changelog
---------
- Enabled i18n on landing page supporting EN & ZH
- Temporarily remove contributor list because upstream is down
Checklist
---------
Reference
---------
- [React-i18next Quick start](https://react.i18next.com/guides/quick-start)
- [Auto detect the user language](https://react.i18next.com/legacy-v9/step-by-step-guide#c-auto-detect-the-user-language)
=> Enable i18n on landing page

.github/workflows/contributors.yml, README.md
Changelog
---------
Checklist
---------
=> Auto update contributor on every master commit

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Use 'HashiCorp AWS' action for deployment

packages/messier-61-app/README.md
Changelog
---------
Checklist
---------
=> Update landing page README

.github/workflows/ci-cd.yml, babel.config.json, packages/messier-61-app/package.json, packages/messier-61-app/src/components/Team.jsx, packages/messier-61-app/src/components/Team.test.jsx, packages/messier-61-app/src/components/__snapshots__/Team.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/about.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/footer.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/header.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/image.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/navigation.test.jsx.snap, packages/messier-61-app/src/components/__snapshots__/services.test.jsx.snap, packages/messier-61-app/src/components/about.jsx, packages/messier-61-app/src/components/about.test.jsx, packages/messier-61-app/src/components/footer.jsx, packages/messier-61-app/src/components/footer.test.jsx, packages/messier-61-app/src/components/header.jsx, packages/messier-61-app/src/components/header.test.jsx, packages/messier-61-app/src/components/image.test.jsx, packages/messier-61-app/src/components/navigation.jsx, packages/messier-61-app/src/components/navigation.test.jsx, packages/messier-61-app/src/components/services.jsx, packages/messier-61-app/src/components/services.test.jsx, packages/messier-61-app/yarn.lock
Changelog
---------
- 添加了关于Landing Page 的测试，使用Jest的`Snapshot Testing `方法对首页的 `About`、`Footer`等各个模块进行单元测试。
- 添加了Snapshot 测试的相关依赖。
- 修改了CI/CD 配置中`test`的指令。
Checklist
---------
=> Add Landing Page Test

README.md, packages/messier-61-graph/src/visualization-view/VisualizationView.tsx
Changelog
---------
- 新建 pull request 或者有新的代码提交都会触发对这个 PR 分支的[SonarCloud 代码质量分析](https://sonarcloud.io/project/overview?id=paion-data_Messier-61)，并生成分析结果，如果分析出严重问题，将导致 Pull request checks 不通过
- Pull request 合并之后在 `master` 分支也会触发代码质量分析，并在项目顶级 README 里面显示当前 `master` 分支代码的分析结果：
- **Messier-61 配备了 SonarCloud 自动分析之后，可以通过其 [REST API](https://sonarcloud.io/api/project_pull_requests/list?project=paion-data_Messier-61) 获取并分析相关数据，最终将作为我们的绩效和晋升考核的科学客观依据**
Checklist
---------
=> 添加 SonarCloud 代码分析徽章

package.json, packages/messier-61-app/src/App.tsx, packages/messier-61-app/src/styled.ts, packages/messier-61-graph/package.json, packages/messier-61-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
- 添加了Styled Components,其中包括`AppWrapper`、`GraphBrowserWrapper`和`EditorWrapper`，分别用来定义`App`、`GraphBrowser`、`EditorWrapper`这三个组件的风格样式
- 将原来在messier-61-app/package.json下的styled-components下的依赖移动到顶级的package.json下
Checklist
---------
=> Setting App Style

packages/messier-61-graph/src/GraphStyle.ts, packages/messier-61-graph/src/GraphVisualizer.tsx, packages/messier-61-graph/src/inspection-panel/NodeLabel.tsx, packages/messier-61-graph/src/inspection-panel/properties-panel-content/properties-panel-content/DetailsPane.tsx, packages/messier-61-graph/src/shared/editor/editorDuck.ts
Changelog
---------
- 支持`NodeInspectorPanel`面板展开功能
- 修复了`GraphStyle`中影响面板展开的函数`getDefaultNodeCaption`，利用`@ts-expect-error ts-migrate(2365)`解决判断的编译报错
Checklist
---------
=> Support Node Pane Expansion

packages/messier-61-graph/src/event-handler/NodeEventHandler.ts, packages/messier-61-graph/src/event-handler/RelationshipEventHandlers.ts
Changelog
---------
Checklist
---------
=> Graph Event Handler Debug

packages/messier-61-app/src/App.tsx, packages/messier-61-app/src/styled.ts, packages/messier-61-editor/src/Lexical/LexicalEditor.module.css, packages/messier-61-graph/src/Graph.tsx, packages/messier-61-graph/src/WheelZoomInfoOverlay.tsx, packages/messier-61-graph/src/styles/DefaultPane.styled.ts, packages/messier-61-graph/src/styles/InspectorContainer.styled.ts
Changelog
---------
- 添加App整体模块的style
- 修改`NodeInspectorPanel`的风格样式
- 暂时注释掉Graph中Zoom相关的按钮
Checklist
---------
=> Page Style Definition

hashicorp/instances/app.tf
Changelog
---------
Checklist
---------
=> Fix domain typo

.github/workflows/ci-cd.yml, packages/nexusgraph-app/package.json, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/index.tsx, yarn.lock
Changelog
---------
- 初步实现基于 [sentry.io](https://sentry.io/) Nexus Graph 的业务监控能力
Checklist
---------
=> Enable sentry.io monitoring for app.nexusgraph.com

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphVisualizer.tsx, packages/nexusgraph-graph/src/Visualization.ts, packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts, packages/nexusgraph-graph/src/event-handler/NodeEventHandler.ts, packages/nexusgraph-graph/src/event-handler/RelationshipEventHandlers.ts, packages/nexusgraph-graph/src/inspection-panel/DefaultDetailsPane.tsx, packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx, packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/DetailsPane.tsx, packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/OverviewPane.tsx, packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/StyleableNodeLabel.tsx, packages/nexusgraph-graph/src/inspection-panel/properties-panel-content/properties-panel-content/StyleableRelType.tsx, yarn.lock
Changelog
---------
- 添加节点和关系的详情面板
Checklist
---------
=> Implement Item Details Panel

packages/nexusgraph-app/src/index.tsx, packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.test.tsx, packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx, packages/nexusgraph-editor/src/Lexical/processor/NaturalLanguageProcessor.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts, packages/nexusgraph-graph/src/Graph.tsx, packages/nexusgraph-graph/src/shared/editor/editorDuck.ts
Changelog
---------
- 联接editor and graphing via Redux
- 编写editorReducer测试
- 添加axios mock测试
- 更改axios获取并解析的代码，使得数据可以异步获取
Checklist
---------
=> Add test for connecting editor and graphing via Redux

.github/workflows/ci-cd.yml, hashicorp/images/aws-nexusgraph-app.pkr.hcl, hashicorp/scripts/setup-app.sh
Changelog
---------
- 修复 app.nexusgraph.com 访问异常的问题，原因是最近引入的 .env 文件没有打进 IAM 镜像，导致在 IAM 镜像里面编译的时候报错，最后 Nexus Graph 无法正常启动
Checklist
---------
=> Load environment variable file into IAM

.github/workflows/ci-cd.yml, .gitignore, cypress.config.ts, cypress/e2e/nexusgraph.spec.cy.ts, cypress/e2e/spec.cy.ts, cypress/fixtures/getEditorData.json, cypress/fixtures/nodeExpandData.json, docs/docs/development/environment.md, package.json, scripts/start.js, scripts/wait-on-config.js, yarn.lock
Changelog
---------
- 添加基础的E2E Test，保证App基础功能正常
- 将E2E Test 部署到CI/CD
Checklist
---------
=> Add nexusgraph basic e2e test

cypress/e2e/nexusgraph.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts, packages/nexusgraph-graph/src/GraphGeometryModel.ts
Changelog
---------
- 为`GraphGeometryModel`添加部分文档
- 修改了设置节点中每行位置的函数`fitOnFixedNumberOfLines`，在原有的基础上添加一部分逻辑，将文本集中在节点中间
- 将`ENTITY_EXTRACTION_API_URL`的参数修改为`text`
Checklist
---------
=> Node Text Position Ddebug

cypress/e2e/NodeInspectorPanel.spec.cy.ts, cypress/fixtures/single-rdf-pair-graph.json, packages/nexusgraph-graph/src/GraphVisualizer.tsx, packages/nexusgraph-graph/src/inspection-panel/NodeInspectorPanel.tsx
Changelog
---------
- 修复第一次出图，统计面板节点总数展示不正确的问题
Checklist
---------
=> Fix 'all nodes (*) count is always 0 at initial rendering' issue

packages/nexusgraph-graph/src/GraphVisualizer.tsx
Changelog
---------
- 暂时注释掉展开邻居节点数量超过限制时的警告
Checklist
---------
=> Comment panel warning

cypress/e2e/NodeInspectorPanel.spec.cy.ts, cypress/e2e/nexusgraph.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.test.ts, packages/nexusgraph-editor/src/Lexical/processor/RemoteNaturalLanguageProcessor.ts, packages/nexusgraph-graph/src/processor/NodesExpand.ts
Changelog
---------
- 编辑器文字分析和展开调用的后端接口变更为 POST
Checklist
---------
=> Integrate Prometheus caching service

cypress/e2e/NodeInspectorPanel.spec.cy.ts, packages/nexusgraph-graph/src/processor/NodesExpand.test.ts, packages/nexusgraph-graph/src/processor/NodesExpand.ts
Changelog
---------
Checklist
---------
=> Add expand processor test

packages/nexusgraph-app/src/styled.ts, packages/nexusgraph-editor/src/Lexical/LexicalEditor.module.css
Changelog
---------
- 修改 editor 样式， 解决editor超出屏幕问题
Checklist
---------
=> Fix editor out-of-screen issue

cypress/e2e/editor.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/plugins/NexusgraphOnChangePlugin.tsx, packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.js, packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Changelog
---------
- Editor只更新style时，不触发重新做图
- 完成 toorbar E2E test
- 完善链接弹窗溢出页面的问题
- 补充下拉菜单ul ol 添加粗体等样式的style
Checklist
---------
=> editor-optimization 

cypress/e2e/editor.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx, packages/nexusgraph-editor/src/Lexical/plugins/styled.ts, packages/nexusgraph-editor/src/Lexical/themes/ExampleTheme.js
Changelog
---------
- 完善toobarplugin标题按钮
- 添加标题的e2e test
Checklist
---------
=> Add heading to level-six

packages/nexusgraph-app/src/styled.ts
Changelog
---------
- 加大 App 与屏幕边缘间的距离，以及 Editor 与Graph 间的距离
Checklist
---------
=> Adjust app margin

.github/workflows/ci-cd.yml, cypress.config.ts, cypress/e2e/0.login.spec.cy.ts, cypress/e2e/NodeInspectorPanel.spec.cy.ts, cypress/e2e/editor.spec.cy.ts, cypress/e2e/nexusgraph.spec.cy.ts, cypress/support/commands.ts, cypress/support/global.d.ts, docs/docs/development/environment.md, package.json, packages/nexusgraph-app/package.json, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/LogtoProvider.tsx, packages/nexusgraph-app/src/index.tsx, tsconfig.json, yarn.lock
Changelog
---------
- Put APP behind a login page
Checklist
---------
=> Implement login page

cypress/e2e/editor.spec.cy.ts
Changelog
---------
- 解决了`editor.spec.cy.ts` 中，两个 `beforeEach` 冲突的问题
Checklist
---------
=> E2e test change

.github/workflows/ci-cd.yml, cypress/e2e/editor.spec.cy.ts, docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/environment.md, hashicorp/images/nginx-ssl-app.conf, hashicorp/instances/app.tf, hashicorp/scripts/setup-app.sh, package.json
Changelog
---------
- 完善 CI/CD 可读性
- 将 E2E 测试放到 dev(开发) 和 prod(生产)环境测试两次，保证 test concern 分离的同时，确保生产环境的功能正常运行
- 如果 dev 的 E2E 测试失败，则代表代码逻辑 concern 出现问题
- 如果 dev 通过，但是 prod 的 E2E 测试失败，则代表环境配置 concern 出现问题
- 删除无用注释 (`# https://stackoverflow.com/a/67740771`)
- 🔥 **修复生产环境无法完成登录跳转进入主页面的问题**，方法是使用 **[serve](https://github.com/vercel/serve)** 替换之前的 Python 服务器来运行 nexusgraph
Checklist
---------
来审核，让大家都理解生产环境的相关部署
=> Fix the login redirect issue in production

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Running unit and e2e tests in parallel

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
反映出来的严重问题
---------------
- 代码审核人不够细致，日后**必须加强**
- 开发同学还不能同时操控运维和开发两大块内容，需要先专注于开发
=> Add logto config to prod instance

.github/workflows/ci-cd.yml, packages/nexusgraph-app/src/App.tsx
Changelog
---------
- 开发和生产环境下通过环境变量 [NODE_ENV](https://stackoverflow.com/a/58232503) 自动切换 OAuth redirect
Checklist
---------
=> Add redirect in prod environment

packages/nexusgraph-graph/src/VisualizationView.tsx
Changelog
---------
- 为解决master分支上 sonar cloud 报错的问题， 暂时将 `VisualizationView`中转换`BasicNode`和`BasicRelationship`的`map`方法改为 `forEach`的方法
Checklist
---------
=> Fix master sonar cloud error

cypress/e2e/align-dropdown.spec.cy.ts, cypress/e2e/editor.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/plugins/RichTextDropDown.tsx, packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.test.tsx, packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx, packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Changelog
---------
- Add indent and outdent button
- Write indent and outdent button e2e test and unit test
- [Optimize the indentation of all text in the editor](https://playground.lexical.dev/)
- Put LeftAlign RightAlign CenterAlign and JustifyAlign  into the dropdown menu
- Change LeftAlign RightAlign CenterAlign and JustifyAlign unit test
Checklist
---------
=> Add indent and outdent button

cypress/e2e/clear-formatting.spec.cy.ts, packages/nexusgraph-editor/src/Lexical/plugins/ToolbarPlugin.tsx, packages/nexusgraph-editor/src/Lexical/plugins/styled.ts
Changelog
---------
- Add clear formatting button
- Write clear formatting e2e test
- [Clear list, heading, quote format needs to be improved](https://playground.lexical.dev/)
- Change FontDropDown styled.ts 
Checklist
---------
=> Add clear formatting button

.github/dbInDev.json, .github/dbInProd.json, .github/workflows/ci-cd.yml, cypress/e2e/0.login.spec.cy.ts, cypress/e2e/align-dropdown.spec.cy.ts, cypress/e2e/editor.spec.cy.ts, cypress/e2e/font-family-dropdown.spec.cy.ts, cypress/e2e/font-size-dropdown.spec.cy.ts, cypress/e2e/nexusgraph.spec.cy.ts, cypress/e2e/node-inspector-panel.spec.cy.ts, jest.config.json, packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts, packages/nexusgraph-server/package.json, packages/nexusgraph-server/src/server.test.ts, packages/nexusgraph-server/src/server.ts, packages/nexusgraph-server/yarn.lock
Changelog
---------
- 为 nexusgraph-server 添加测试 确保node.js服务器可以成功访问并传递JSON数据
- Server 使用传递参数的方式配置db.json，并在ci/cd 中配置
- 移除e2e测试中的 wait ，这将使用 [cypress 中的默认值 ](https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test)wait(4000)
Checklist
---------
=> The server configures db.json by passing parameters

package.json, packages/nexusgraph-app/package.json, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/AppInit.test.tsx, packages/nexusgraph-app/src/AppInit.tsx, packages/nexusgraph-app/src/DevApp.tsx, packages/nexusgraph-app/src/ProdApp.tsx, packages/nexusgraph-app/src/index.tsx, packages/nexusgraph-oauth2/index.ts, packages/nexusgraph-oauth2/package.json, packages/nexusgraph-oauth2/src/OAuth2Provider.tsx, packages/nexusgraph-oauth2/src/useOAuth2.ts, yarn.lock
Changelog
---------
- In order to abstract away the OAuth logics, a new **nexusgraph-oauth2** package has been created
- All [logto](https://logto.io/) dependencies have been confined in nexusgraph-oauth2 package
- Implemented [OAuth2 custom hook](https://github.com/paion-data/nexusgraph/pull/190/files#diff-698d3542699c7b8976b30a4f62e6a340f9683efe1869967e6ef9f85d11525d9b) that _is responsible for controlling Auth contextin App_
- Inject the OAuth2 custom hook via component Props in order to enable real OAuth context via Logto in ProdApp and Fake OAuth context in DevApp
- Bumped Sentry setup from ProdApp into AppInit level function
Checklist
---------
Reference
---------
- [Logto React](https://docs.logto.io/docs/recipes/integrate-logto/react/)
- [Logto API …
=> Login refactoring

packages/nexusgraph-app/src/ReduxHook.tsx, packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx, packages/nexusgraph-redux/src/note/noteDuck.ts, packages/nexusgraph-redux/src/note/noteTypes.ts
Changelog
---------
- 实现了用户点击新建笔记按钮时，在数据库中新建一篇笔记
Checklist
---------
=> Implementation create new note

.env.test, .github/workflows/ci-cd.yml, packages/nexusgraph-app/public/index.html
Changelog
---------
- Add the environment variable `LOGTO_SIGN_IN_CALLBACK_URL` in CI/CD and `.env.test`
- Changed the import path of the manifest file in index.html
Checklist
---------
=> Import manifest.json file in index.html

package.json, packages/nexusgraph-redux/src/StoreProvider.tsx, yarn.lock
Changelog
---------
- Remove redux toolkit dependency, and used  `redux`  creat redux store
- Demoted "redux" dependency version to "^3.7.2"
Checklist
---------
=> Remove redux toolkit dependency

packages/nexusgraph-app/src/AstraiosClientHook.ts, packages/nexusgraph-app/src/ReduxHook.tsx, packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx, packages/nexusgraph-app/src/editor-button-group/styled.ts, packages/nexusgraph-astraios/src/AstraiosClient.ts, packages/nexusgraph-astraios/src/GraphqlAstraiosClient.ts, packages/nexusgraph-astraios/src/JsonApiAstraiosClient.ts, packages/nexusgraph-editor/src/Lexical/plugins/EditorInitializationPlugin.ts, packages/nexusgraph-redux/src/note-list/noteListDuck.ts, packages/nexusgraph-redux/src/note/noteDuck.ts, packages/nexusgraph-redux/src/oAuth/oAuthDuck.ts
Changelog
---------
- Implement note creation and deletion
- Rename the function `getFirstNote  => getNotebyId` in `GraphQlClient`
Checklist
---------
=> Implement note creation and deletion

.env.test, .github/workflows/ci-cd.yml, cypress.config.ts, packages/nexusgraph-astraios/src/GraphqlAstraiosClient.ts, packages/nexusgraph-astraios/src/JsonApiAstraiosClient.ts, packages/nexusgraph-oauth/src/OAuth2Provider.tsx
Changelog
---------
- Merge the original `ASTRAIOS_GRAPHQL_API_ENDPOINT` and `ASTRAIOS_JSON_API_ENDPOINT` environment variables into `ASTRAIOS_API_RESOURCE`
Checklist
---------
=> Environment variable change

packages/nexusgraph-app/src/AstraiosClientHook.ts, packages/nexusgraph-app/src/ReduxHook.tsx, packages/nexusgraph-app/src/editor-button-group/EditorButtonGroup.tsx, packages/nexusgraph-astraios/src/AstraiosClient.ts, packages/nexusgraph-astraios/src/GraphqlAstraiosClient.ts, packages/nexusgraph-editor/src/Lexical/plugins/EditorContentUpdatePlugin.ts
Changelog
---------
- Add headers for GraphQL requests in `GraphQlClient`
Checklist
---------
=> Add headers for GraphQL requests

.github/workflows/ci-cd.yml, hashicorp/images/aws-app-nexusgraph-com.pkr.hcl, hashicorp/instances/app-nexusgraph-com.tf, hashicorp/scripts/aws-app-nexusgraph-com-pkr-setup.sh
Changelog
---------
- Enhanced wordings of CI/CD definitions to make it more readable
- Fixed the problem of current deployment being hanged due to the EC2 region unspecified
Checklist
---------
=> Fix deployment error

.env.test, packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx, packages/nexusgraph-app/src/sidebar/styled.ts, packages/nexusgraph-app/src/styled.ts, packages/nexusgraph-graph/src/styles/WheelZoomInfoOverlay.styled.ts
Changelog
---------
- Minor issues in the style of the App， such as: the position of the text on the button and the modal's position 
- Update `.env.test` file
Checklist
---------
=> App style change

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Wait for the test to pass and then publish

cypress/e2e/i18n.spec.cy.ts, cypress/support/commands.ts, cypress/support/global.d.ts, packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx, packages/nexusgraph-i18n/index.ts, packages/nexusgraph-i18n/src/graph/graph.json, packages/nexusgraph-redux/src/note/noteDuck.ts
Changelog
---------
- Perfect i18n translation，the main realization of note title and intelligent AI button translation
- Add i18n E2E test
Checklist
---------
=> Perfect i18n

.github/workflows/ci-cd.yml, packages/nexusgraph-app/src/Loadingpage.tsx, packages/nexusgraph-app/src/ProdApp.tsx, packages/nexusgraph-app/src/styled.ts, packages/nexusgraph-oauth/src/OAuth2Provider.tsx
Changelog
---------
- Add `Loadingpage` component, used to wait for `Logto` to load
Checklist
---------
=> Add loadingpage

packages/nexusgraph-app/src/ProdApp.tsx
Changelog
---------
- Fixed the problem that the logged-in user enters the error page when accessing the App again,  render the [App](https://github.com/paion-data/nexusgraph/blob/master/packages/nexusgraph-app/src/App.tsx) component directly if the user is logged in
Checklist
---------
=> Fix prod-app bug

packages/nexusgraph-app/src/sidebar/FeatureMenu.tsx, packages/nexusgraph-app/src/sidebar/styled.ts
Changelog
---------
- Add button hover style
- Fixed a bug in i18n translation，define the button lable before rendering the component
Checklist
---------
=> Add button hover style

packages/nexusgraph-graph/src/GraphStyle.ts, packages/nexusgraph-graph/src/styles/WheelZoomInfoOverlay.styled.ts
Changelog
---------
- Fixed an issue where relationship text was unsharp
Checklist
---------
=> Change for relationship style

.env.test, packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.test.ts, packages/nexusgraph-nlp/src/processor/RemoteNaturalLanguageProcessor.ts
Changelog
---------
- Change the NLP entity extraction request endpoint
Checklist
---------
=> Connect to theresa Middleware

packages/nexusgraph-app/inversify.config.ts, packages/nexusgraph-app/src/DevApp.tsx, packages/nexusgraph-app/src/ProdApp.tsx
Changelog
---------
Checklist
---------
=> Bind access token and user id to app context

packages/nexusgraph-redux/index.ts, packages/nexusgraph-redux/src/graph/graphDuck.ts
Changelog
---------
Checklist
---------
=> Do not export everything from graph state

cypress/e2e/entity-extraction.spec.cy.ts, cypress/fixtures/single-rdf-tuple-from-theresa.json
Changelog
---------
- Prepare for the next iteration of refactoring by adding tests
Checklist
---------
=> Add test for entity extraction feature

packages/nexusgraph-app/src/component/sidebar/FeatureMenu.tsx
Changelog
---------
Checklist
---------
=> Early-return when inference result is empty

packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/styled.ts
Changelog
---------
Checklist
---------
=> Renaming SideBar as a styled-component

packages/nexusgraph-astraios/src/AstraiosClient.ts
Changelog
---------
Checklist
---------
Reference
---------
- [Has been blocked by CORS policy: Response to preflight request doesn’t pass access control check](https://stackoverflow.com/a/53304135)
=> Allow CORS

packages/nexusgraph-astraios/src/AstraiosClient.ts
Reverts paion-data/nexusgraph#261
=> Revert "Allow CORS"

packages/nexusgraph-app/src/component/sidebar/FeatureMenu.tsx, packages/nexusgraph-astraios/src/AstraiosClient.ts
Changelog
---------
Checklist
---------
=> Fix issue where graph object is not serialized properly during save

packages/nexusgraph-graph/src/GraphVisualizer.tsx, packages/nexusgraph-graph/src/Visualization.ts, packages/nexusgraph-graph/src/VisualizationView.tsx, packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.test.ts, packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts, packages/nexusgraph-graph/src/event-handler/index.ts, packages/nexusgraph-redux/src/graph/graphDuck.ts
Changelog
---------
Checklist
---------
=> Support double-clicking canvas creates new node

packages/nexusgraph-graph/src/VisualizationView.tsx, packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.test.ts, packages/nexusgraph-graph/src/event-handler/GraphEventHandlerModel.ts, packages/nexusgraph-graph/src/event-handler/NodeEventHandler.ts, packages/nexusgraph-graph/src/event-handler/index.ts
Changelog
---------
Checklist
---------
=> Support on-canvas link creation via alt-clicking

packages/nexusgraph-app/src/component/sidebar/NewGraphButton.tsx, packages/nexusgraph-app/src/component/sidebar/SideBar.tsx, packages/nexusgraph-app/src/component/sidebar/styled.ts
Changelog
---------
Checklist
---------
=> Renaming button for creating a new graph

package.json, packages/nexusgraph-app/package.json, yarn.lock
Changelog
---------
Checklist
---------
=> Push react-bootstrap down to app package

packages/nexusgraph-app/src/component/sidebar/Modal.tsx, packages/nexusgraph-app/src/component/sidebar/styled.ts
Changelog
---------
Checklist
---------
Reference
---------
- [React styled-components fade in/fade out](https://stackoverflow.com/a/41973695)
- [Using CSS for a fade-in effect on page load](https://stackoverflow.com/questions/11679567/using-css-for-a-fade-in-effect-on-page-load#:~:text=%40keyframes%20fadein%20%7B-,from%20%7B%20opacity%3A%200%3B%20%7D%0A%20%20%20%20to%20%20%20%7B%20opacity%3A%201%3B%20%7D,-%7D%0A%0A/*%20Firefox%20%3C%2016)
=> Implement modal transition effect

cypress/e2e/alert.spec.cy.ts, cypress/e2e/entity-extraction.spec.cy.ts, package.json, packages/nexusgraph-app/src/component/sidebar/new-graph-button/MethodModal.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/MethodsSelectionModal.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/NewGraphButton.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/methods.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/styled.ts, packages/nexusgraph-app/src/component/sidebar/styled.ts, packages/nexusgraph-i18n/src/graph/graph.json
Changelog
---------
- From this PR on, all Cypress E2E runs against **chrome** only
Checklist
---------
Reference
---------
- [Looping-through a map to generate list of components](https://stackoverflow.com/a/51642595)
=> E2E runs against Chrome ONLY & NewGraphButton controls 2 separate modals

cypress/e2e/alert.spec.cy.ts, cypress/e2e/entity-extraction.spec.cy.ts, cypress/fixtures/astraios-graphql-response.json, cypress/support/commands.ts, cypress/support/global.d.ts
Changelog
---------
Checklist
---------
=> Promote GraphQL request interception to a Cypress command

cypress/e2e/new-graph-button.spec.cy.ts
Changelog
---------
Checklist
---------
=> Add E2E tests for new graph button

.eslintrc.json, cypress/e2e/new-graph-button.spec.cy.ts, packages/nexusgraph-app/src/component/sidebar/new-graph-button/MethodsSelectionModal.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/styled.ts
Changelog
---------
Checklist
---------
=> Add new NLP button icon

packages/nexusgraph-graph/public/save.svg
Changelog
---------
Checklist
---------
=> Delete unused svg

packages/nexusgraph-app/src/component/sidebar/new-graph-button/NewGraphButton.tsx
Changelog
---------
Checklist
---------
=> No need for icon intermediate decl.

packages/nexusgraph-app/src/component/GraphNameInput.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/styled.ts, packages/nexusgraph-app/src/component/styled.ts, packages/nexusgraph-graph/src/styles/ExportButtn.styled.ts, packages/nexusgraph-graph/src/styles/InspectorContainer.styled.ts, packages/nexusgraph-graph/src/styles/PropertiesTable.styled.ts
Changelog
---------
Checklist
---------
=> Remove z-index

package.json, packages/nexusgraph-graph/package.json, yarn.lock
Changelog
---------
Checklist
---------
=> Relocate icons library

packages/nexusgraph-app/src/DevApp.tsx, packages/nexusgraph-app/src/ProdApp.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/methods.tsx, packages/nexusgraph-astraios/src/AstraiosClient.ts, packages/nexusgraph-graph/src/VisualizationView.tsx
Changelog
---------
Checklist
---------
=> Push user id and access token into AstraiosClient states

packages/nexusgraph-app/src/component/sidebar/new-graph-button/styled.ts
Changelog
---------
Checklist
---------
=> Remove unused defs in modal content styling

cypress/fixtures/astraios-graphql-response.json, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/AppInit.tsx, packages/nexusgraph-app/src/DevApp.tsx, packages/nexusgraph-app/src/ProdApp.tsx, packages/nexusgraph-app/src/component/DeleteButton.tsx, packages/nexusgraph-app/src/component/index.ts, packages/nexusgraph-app/src/component/styled.ts, packages/nexusgraph-astraios/src/AstraiosClient.ts
Changelog
---------
Checklist
---------
=> Implement graph delete && Initialize graph area with the first graph in list

packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/sidebar/SideBar.tsx
Changelog
---------
Checklist
---------
=> Implement switching displayed graph by sidebar

.github/workflows/ci-cd.yml, cypress/e2e/alert.spec.cy.ts, cypress/e2e/new-graph-button.spec.cy.ts
Changelog
---------
Checklist
---------
=> E2E testing runs against a real Astraios in Docker Compose

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Use new action reference

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> New action reference for unit tests

packages/nexusgraph-app/src/component/sidebar/new-graph-button/methods.tsx
Changelog
---------
Checklist
---------
=> Auto-gen graph ID should be pushed to Redux as well

cypress/e2e/alert.spec.cy.ts, cypress/e2e/delete-button.spec.cy.ts, cypress/support/commands.ts, cypress/support/global.d.ts, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/DeleteButton.tsx, packages/nexusgraph-app/src/component/sidebar/SideBar.tsx, packages/nexusgraph-app/src/component/styled.ts
Changelog
---------
Checklist
---------
Reference
---------
- [How to disable button in React.js](https://stackoverflow.com/questions/41488715/how-to-disable-button-in-react-js#:~:text=%3Cbutton%20disabled%3D%7B!this.state.value%7D%20/%3E)
- [conditional rendering in styled components](https://stackoverflow.com/questions/48502647/conditional-rendering-in-styled-components#:~:text=%24%7B(%7B%20active%20%7D)%20%3D%3E%20active%20%26%26%20%60%0A%20%20%20%20background%3A%20blue%3B%0A%20%20%60%7D)
- [How to check a button is disabled using Cypress](https://sqa.stackexchange.com/a/41572)
- [Cypress use regex to retrieve elements with matching text in id](https://stackoverflow.com/a/61334719)
=> Delete button tests

cypress/e2e/side-bar.spec.cy.ts
Changelog
---------
Checklist
---------
=> Add E2E tests for side bar

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Fix wording

cypress/e2e/app.spec.cy.ts, packages/nexusgraph-app/src/App.tsx
Changelog
---------
Checklist
---------
=> Deleting the last graph should not remove the entire graph list

cypress/e2e/app.spec.cy.ts, cypress/e2e/delete-button.spec.cy.ts, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/DeleteButton.tsx, packages/nexusgraph-app/src/component/styled.ts
Changelog
---------
Checklist
---------
Reference
---------
- [Styling button with SVG label](https://stackoverflow.com/a/70052092)
- [Type 'Element | undefined' is not assignable to type 'ReactElement<any, string | ((props: any)](https://stackoverflow.com/a/75130652)
=> Delete button should not show up when user hasn't create any graph yet

.github/workflows/ci-cd.yml, README.md, package.json
Changelog
---------
Checklist
---------
=> Use Node 18

cypress/e2e/alert.spec.cy.ts, cypress/e2e/graph-title.spec.cy.ts, cypress/e2e/i18n.spec.cy.ts, cypress/support/commands.ts, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/GraphTitle.tsx
Changelog
---------
Checklist
---------
=> Title section should not show when no graph is created

cypress/e2e/app.spec.cy.ts, cypress/e2e/delete-button.spec.cy.ts
Changelog
---------
Checklist
---------
=> Move common assertion  into command

packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/DeleteButton.tsx
Changelog
---------
Checklist
---------
=> Graph ID can't be null

cypress/e2e/graph-title.spec.cy.ts, cypress/e2e/i18n.spec.cy.ts, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/component/GraphTitle.tsx, packages/nexusgraph-redux/src/graph-list/graphListDuck.ts
Changelog
---------
Checklist
---------
=> Implement title update

cypress/e2e/graph-title.spec.cy.ts, packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-redux/src/graph-list/graphListDuck.ts
Changelog
---------
Checklist
---------
Reference
---------
- [react-redux update item in array doesn't re-render](https://stackoverflow.com/a/39667908)
=> Updating title should refresh sidebar list immediately

packages/nexusgraph-app/src/component/sidebar/SideBar.tsx, packages/nexusgraph-app/src/component/sidebar/new-graph-button/NewGraphButton.tsx, packages/nexusgraph-app/src/component/sidebar/styled.ts
Changelog
---------
Checklist
---------
=> Highlight selected graph in sidebar list

.github/workflows/ci-cd.yml, cypress.config.ts, cypress/e2e/graph-title.spec.cy.ts, packages/nexusgraph-app/src/component/sidebar/styled.ts, packages/nexusgraph-app/src/styled.ts
Changelog
---------
Checklist
---------
Reference
---------
- [Button minimum width](https://defensivecss.dev/tip/button-min-width/)
- [min-width](https://css-tricks.com/almanac/properties/m/min-width/)
- [Cypress retries](https://docs.cypress.io/guides/guides/test-retries#Global-Configuration)
=> Optimize E2E retry strategy & shrinking effect of sidebar

packages/nexusgraph-graph/package.json, yarn.lock
Changelog
---------
Checklist
---------
=> Remove unused dependency

cypress/e2e/app.spec.cy.ts, cypress/support/commands.ts, package.json, packages/nexusgraph-redux/package.json, yarn.lock
Changelog
---------
Checklist
---------
=> Fix wrong workspaces && Fix flaky newGraph Cypress command && Fix flaky app E2E

docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development/10-architecture.md
Changelog
---------
Checklist
---------
=> Fix broken link

.env.test, packages/nexusgraph-app/src/ProdApp.tsx
Changelog
---------
Checklist
---------
Reference
---------
- [If re-signin is not there](https://openid.sh/debug/invalid_grant)
=> Redirect to sign-in when refresh token expires

README.md, cypress/support/commands.ts
Changelog
---------
Checklist
---------
=> Enhance version badge

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
Checklist
---------
=> Disable NodeInspectionPanel for now

cypress/e2e/app.spec.cy.ts, cypress/support/commands.ts, packages/nexusgraph-app/src/component/styled.ts
Changelog
---------
Checklist
---------
Reference
---------
- [How TO - Responsive Text](https://www.w3schools.com/howto/howto_css_responsive_text.asp)
=> Responsive graph title font size

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
Checklist
---------
=> Fix app crashing issue by on-canvas node creation

docs/docs/development/5-environment.md, packages/nexusgraph-graph/package.json, yarn.lock
Changelog
---------
Checklist
---------
Reference
---------
- https://github.com/QubitPi/neo4j-browser/pull/26
=> Use new version of arc

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
Checklist
---------
=> Turn on node inspector panel

cypress/e2e/i18n.spec.cy.ts, package.json, packages/nexusgraph-app/src/i18n.ts, yarn.lock
Changelog
---------
Checklist
---------
=> Auto detect and set language

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, packages/nexusgraph-graph/src/themes.ts, yarn.lock
Changelog
---------
Checklist
---------
=> Customize details pane styles

packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
Checklist
---------
=> Make table properties & link label editable

README.md
Changelog
---------
Checklist
---------
=> Add reference citation

packages/nexusgraph-app/src/App.tsx, packages/nexusgraph-app/src/styled.ts
Changelog
---------
Enhanced left alignment of App according to _Non-Designers Design Book_:
Checklist
---------
=> Unify left alignment of app header/body/footer sections

cypress/e2e/node-inspectior-panel.spec.cy.ts, cypress/e2e/viz.spec.cy.ts, cypress/support/commands.ts, cypress/support/global.d.ts, packages/nexusgraph-graph/package.json, packages/nexusgraph-graph/src/GraphBrowser.tsx, yarn.lock
Changelog
---------
Checklist
---------
=> Complete E2E tests on on-canvas operation

.github/workflows/ci-cd.yml, cypress/e2e/screenshot.spec.cy.ts, cypress/tsconfig.json, docs/docs/development/5-environment.md, package.json, yarn.lock
Changelog
---------
Checklist
---------
=> Add Argos Visual Testing

.github/lighthouse/formatLighthouseReport.js, .github/lighthouse/lighthouse-budget.json, .github/lighthouse/lighthouserc.json, .github/lighthouse/package.json, .github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Integrate Lighthouse CI

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Fix deployment issue

.github/workflows/ci-cd.yml, packages/nexusgraph-app/src/ProdApp.tsx
Changelog
---------
- The login by @Xxy1016 is poorly written
Checklist
---------
=> Enhance poorly written login

packages/nexusgraph-app/src/ProdApp.tsx
Changelog
---------
Checklist
---------
=> TypeDoc is truely an ASSHOLE!

docs/scripts/typedoc.js
Changelog
---------
Checklist
---------
=> Stupid TypeDoc should exit with error if there is any error

.github/workflows/ci-cd.yml
Changelog
---------
Checklist
---------
=> Fix node version placeholder bug

packages/nexusgraph-db/graph.schema
Changelog
---------
Checklist
---------
=> Add JSON schema of GraphQL API response for graph client

.github/workflows/ci-cd.yml, packages/nexusgraph-db/graph.schema
Changelog
---------
Checklist
---------
=> Add JSON schema syntax check in CI/CD

.sonarcloud.properties, README.md
Changelog
---------
Checklist
---------
=> Remove SonarCloud
